{{- if and .Values.enabled (eq .Values.global.monitoring.type "internal") -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus-{{ .Release.Namespace }}
  labels:
    app: prometheus
    chart: {{ template "prometheus.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
rules:
- apiGroups: [""]
  resources:
  - nodes
  - services
  - endpoints
  - pods
  verbs: ["list", "watch"]
- nonResourceURLs: ["/metrics"]
  verbs: ["get"]
{{- end -}}
